"""
update_readme_stats.py — Auto-updates the README with live usage stats.

Reads stats/usage.json, builds a usage table, and writes it into README.md
between marker comments.  Then git-commits and optionally pushes.

Run manually:
    python update_readme_stats.py
    python update_readme_stats.py --push

Or let Claude Code call this automatically after any delegation.
The README will always reflect real numbers from the stats file.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from dotenv import load_dotenv
load_dotenv()

from brain.stats import tracker

_README = Path(__file__).parent / "README.md"

# Markers in README.md that wrap the auto-generated stats block.
_START = "<!-- BRAIN_STATS_START -->"
_END   = "<!-- BRAIN_STATS_END -->"

_TIERS = {
    "groq":         "FREE",
    "gemini":       "FREE",
    "mistral":      "FREE",
    "cerebras":     "FREE",
    "huggingface":  "FREE",
    "pollinations": "FREE",
}


def build_stats_block(stats) -> str:
    """Build the markdown block that gets injected into README.md."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        f"*Last updated: {now} — auto-generated by `update_readme_stats.py`*",
        "",
        "## Live Usage Stats",
        "",
        "| Provider | Tier | Calls | Tokens | Avg Latency | Cost |",
        "|---|---|---|---|---|---|",
    ]

    if not stats.providers:
        lines.append("| — | — | 0 | 0 | — | — |")
    else:
        sorted_providers = sorted(stats.providers.items(), key=lambda x: -x[1].tokens)
        for key, ps in sorted_providers:
            tier     = _TIERS.get(key, "?")
            cost_str = f"${ps.cost_usd:.4f}" if ps.cost_usd else "free"
            lines.append(
                f"| **{key}** | {tier} | {ps.calls:,} | {ps.tokens:,} "
                f"| {ps.avg_latency_ms:.0f}ms | {cost_str} |"
            )

    total_tokens  = stats.total_tokens
    saved_tokens  = stats.claude_tokens_saved
    saved_usd     = stats.estimated_savings_usd
    total_pct     = (saved_tokens / total_tokens * 100) if total_tokens else 0
    free_calls    = sum(
        v.calls for k, v in stats.providers.items() if k != "anthropic"
    )

    lines += [
        "",
        "### Token Savings",
        "",
        f"| Metric | Value |",
        f"|---|---|",
        f"| Total calls | {stats.total_calls:,} |",
        f"| Calls handled by free workers | {free_calls:,} |",
        f"| Tokens offloaded from Claude | {saved_tokens:,} |",
        f"| % of tokens saved | {total_pct:.1f}% |",
        f"| Estimated savings (Claude Sonnet rate) | ${saved_usd:.4f} |",
        f"| Total spend on paid APIs | ${stats.total_cost_usd:.4f} |",
    ]

    if total_tokens and stats.providers:
        lines += [
            "",
            "### Token Distribution",
            "",
            "```",
        ]
        for key, ps in sorted(stats.providers.items(), key=lambda x: -x[1].tokens):
            pct = ps.tokens / total_tokens * 100
            bar = "█" * int(pct / 2)
            tier = _TIERS.get(key, "?")
            lines.append(f"{key:<12} [{tier}]  {bar:<50} {pct:5.1f}%")
        lines.append("```")

    return "\n".join(lines)


def update_readme(stats_block: str) -> bool:
    """Inject stats_block into README.md between the marker comments."""
    if not _README.exists():
        print("README.md not found.")
        return False

    content = _README.read_text(encoding="utf-8")

    if _START not in content:
        # Append markers + block at the end of the file.
        content += f"\n\n{_START}\n{stats_block}\n{_END}\n"
    else:
        # Replace existing block.
        pattern = re.compile(
            rf"{re.escape(_START)}.*?{re.escape(_END)}",
            flags=re.DOTALL,
        )
        content = pattern.sub(f"{_START}\n{stats_block}\n{_END}", content)

    _README.write_text(content, encoding="utf-8")
    return True


def git_commit_and_push(push: bool = False) -> None:
    repo = Path(__file__).parent

    subprocess.run(["git", "add", "README.md", "stats/usage.json"], cwd=repo)
    result = subprocess.run(
        ["git", "commit", "-m",
         "chore: auto-update README with live usage stats\n\nCo-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>"],
        cwd=repo, capture_output=True, text=True
    )
    if "nothing to commit" in result.stdout + result.stderr:
        print("No changes to commit.")
        return

    print("Committed stats update to README.md")
    if push:
        subprocess.run(["git", "push"], cwd=repo)
        print("Pushed to GitHub.")


def main() -> None:
    p = argparse.ArgumentParser(description="Update README with live usage stats")
    p.add_argument("--push", action="store_true", help="Push to GitHub after committing")
    p.add_argument("--dry-run", action="store_true", help="Print block without writing")
    args = p.parse_args()

    stats = tracker.get()
    block = build_stats_block(stats)

    if args.dry_run:
        print(block)
        return

    if update_readme(block):
        print("README.md updated with latest stats.")
        git_commit_and_push(push=args.push)
    else:
        sys.exit(1)


if __name__ == "__main__":
    main()
